name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Run pylint
      run: |
        pylint my_package tests
    - name: Run flake8
      run: |
        flake8 my_package tests
    - name: Run mypy
      run: |
        mypy my_package tests
    - name: Run tests
      run: |
        python3 -m unittest discover -s tests/